### PR TITLE
Upgrade to AWS SDK v3

### PR DESCRIPTION
**Pull request by parisholley**
This change is [Reviewable](https://reviewable.io/reviews/apinstein/shellcommand/8)

### CODE REVIEW

**Comment by apinstein** [comment]
@parisholley did you coordinate this w/Oscar? IIRC there was some problematic stuff about this, since we use the AWS SKD in both ShellCommand and also directly in Nest. I am not sure that the AWS upgrade path was sane (w/r/t being able to use both at same time).

Just surfacing that we need to be sure that this change in ShellCommand doesn't break nest in general, or cause BC issues for any of our projects that require ShellCommand (maybe would need to be sure sensible version number change doesn't import bc-breaking changes?)

That's my only concern.

**Comment by parisholley** [comment]
he didn't think there was any issue. the lambda integration uses a different SDK package and i was able to test this version with the standard upload process without issue.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/shellcommand/8#-:-KagqR_vb4ur6Cl6518m:b8pgqhp)*

**Comment by apinstein** [comment]
That’s a red herring. True, lambda uses something different, but that’s not what I was talking about.

I am surfacing that nest uses ShellCommand (which uses AWS), but in places also uses AWS SDK *directly*. I was concerned what happens when a dependency includes a diff/incompat version of code than the core does:

nest
  +—> use AWSSDK 2.0
  +—> use ShellCommand
       +—> use AWSSDK 3.0

Normally this wouldn’t be an issue, since presumably good SDK’s would be version namespaced? but AWSSDK I don’t think was well-constructed in this fashion.

**Comment by parisholley** [comment]
Nest and Shell was updated to 3.0

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/shellcommand/8#-:-Kah9a5Jk4y6nIUAk0zR:bdsyy7c)*

**Comment by apinstein** [comment]
ok cool! landmine avoided :)

**Comment by jasonbouffard** [comment]
This looks good. We've also been running @parisholley's branch in prod for a while now.

**Pull request merged**
